[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalcdapp = "8G5pZpKZdB8Q5uoSJAog1NYqDvnCMZjxif52FRQeUcKN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\shive\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
